export const GET_COURSES = "GET_COURSES";
export const GET_COURSES_STUDENT_ALL = "GET_COURSES_STUDENT_ALL";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_COURSE_MODULES = "GET_COURSE_MODULES";
export const POST_COURSE = "POST_COURSE";
export const PUT_COURSE = "PUT_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const PATCH_COURSE_PUBLISH = "PATCH_COURSE_PUBLISH";
export const POST_COURSE_MODULE = "POST_COURSE_MODULE";
export const GET_MODULE_LESSONS = "GET_MODULE_LESSONS";
export const POST_COURSE_LESSON = "POST_COURSE_LESSON";
export const POST_COURSE_ENROLL = "POST_COURSE_ENROLL";
export const GET_COURSE_ENROLLMENT_STATUS = "GET_COURSE_ENROLLMENT_STATUS";
export const GET_COURSE_ENROLLMENT = "GET_COURSE_ENROLLMENT";

